aws

diff --git a/{{cookiecutter.project_slug}}/Makefile b/{{cookiecutter.project_slug}}/Makefile
--- a/{{cookiecutter.project_slug}}/Makefile
+++ b/{{cookiecutter.project_slug}}/Makefile
@@ -54,9 +54,13 @@ LOCAL_PORT?=2211
 
 # Google Cloud integration settings:
 GCP_SECRET_FILE?=neuro-job-key.json
-
 GCP_SECRET_PATH_LOCAL=${CONFIG_DIR}/${GCP_SECRET_FILE}
 GCP_SECRET_PATH_ENV=${PROJECT_PATH_ENV}/${GCP_SECRET_PATH_LOCAL}
+
+# AWS integration settings:
+AWS_SECRET_FILE?=aws_credentials
+AWS_SECRET_PATH_LOCAL=${CONFIG_DIR}/${AWS_SECRET_FILE}
+AWS_SECRET_PATH_ENV=${PROJECT_PATH_ENV}/${AWS_SECRET_PATH_LOCAL}
 
 # Weights and Biases integration settings:
 WANDB_SECRET_FILE?=wandb-token.txt
@@ -74,15 +78,24 @@ NEURO?=neuro
 # Check if GCP authentication file exists, then set up variables
 ifneq ($(wildcard ${GCP_SECRET_PATH_LOCAL}),)
 	OPTION_GCP_CREDENTIALS=\
-		--env GOOGLE_APPLICATION_CREDENTIALS=${GCP_SECRET_PATH_ENV} \
-		--env GCP_SERVICE_ACCOUNT_KEY_PATH=${GCP_SECRET_PATH_ENV}
+		--env GOOGLE_APPLICATION_CREDENTIALS="${GCP_SECRET_PATH_ENV}" \
+		--env GCP_SERVICE_ACCOUNT_KEY_PATH="${GCP_SECRET_PATH_ENV}"
 else
 	OPTION_GCP_CREDENTIALS=
 endif
 
+# Check if AWS authentication file exists, then set up variables
+ifneq ($(wildcard ${AWS_SECRET_PATH_LOCAL}),)
+	OPTION_AWS_CREDENTIALS=\
+		--env AWS_CONFIG_FILE="${AWS_SECRET_PATH_ENV}" \
+		--env NM_AWS_CONFIG_FILE="${AWS_SECRET_PATH_ENV}"
+else
+	OPTION_AWS_CREDENTIALS=
+endif
+
 # Check if Weights & Biases key file exists, then set up variables
 ifneq ($(wildcard ${WANDB_SECRET_PATH_LOCAL}),)
-	OPTION_WANDB_CREDENTIALS=--env NM_WANDB_TOKEN_PATH=${WANDB_SECRET_PATH_ENV}
+	OPTION_WANDB_CREDENTIALS=--env NM_WANDB_TOKEN_PATH="${WANDB_SECRET_PATH_ENV}"
 else
 	OPTION_WANDB_CREDENTIALS=
 endif
@@ -196,6 +209,17 @@ gcloud-check-auth:  ### Check if the file containing Google Cloud service accoun
 		&& echo "Google Cloud will be authenticated via service account key file: '$${PWD}/${GCP_SECRET_PATH_LOCAL}'" \
 		|| { echo "ERROR: Not found Google Cloud service account key file: '$${PWD}/${GCP_SECRET_PATH_LOCAL}'"; \
 			echo "Please save the key file named GCP_SECRET_FILE='${GCP_SECRET_FILE}' to './${CONFIG_DIR}/'"; \
+			false; }
+
+##### AWS Integration #####
+
+.PHONY: aws-check-auth
+aws-check-auth:  ### Check if the file containing AWS user account credentials exists
+	@echo "Using variable: AWS_SECRET_FILE='${AWS_SECRET_FILE}'"
+	@test "${OPTION_AWS_CREDENTIALS}" \
+		&& echo "AWS will be authenticated via user account credentials file: '$${PWD}/${AWS_SECRET_PATH_LOCAL}'" \
+		|| { echo "ERROR: Not found AWS user account credentials file: '$${PWD}/${AWS_SECRET_PATH_LOCAL}'"; \
+			echo "Please save the key file named AWS_SECRET_FILE='${AWS_SECRET_FILE}' to './${CONFIG_DIR}/'"; \
 			false; }
 
 ##### WandB Integration #####
